### ISSUE TITLE
Make Bika API work with DX types properly

### ISSUE THREAD

**Issue by ramonski** [bikalabs/bika.lims#2143]
## Description

Currently it is only possible to create Archetypes objects with the API (`bika.lims.api`).
Dexterity contents can't be created and are also not renamed according to the integrated ID Server in Bika LIMS. 

## Todo

- [x] Make `bika.lims.api.create` work with Dexterity contents as well
- [x] Register event handlers for Dexterity types
- [x] Add a behavior for Dexterity content types
- [x] Hook Dexterity content with `bika.lims.idserver.renameAfterCreation`
