### ISSUE TITLE
Buttons, States and Permissions. The List

### ISSUE THREAD

**Issue by lemoene** [bikalabs/bika.lims#895]
There are a number of issues about redundant buttons - consolidated here:
- [ ] 1. [remove] Button on verified Worksheets. Please don't show, https://github.com/bikalabs/Bika-LIMS/issues/801
- [ ] 2. Don't show 'Remove Attachment' icon to users not permitted to use it, https://github.com/bikalabs/Bika-LIMS/issues/755
- [ ] 3. Persistent check-boxes. https://github.com/bikalabs/Bika-LIMS/issues/847, https://github.com/bikalabs/Bika-LIMS/issues/857
- [ ] 4. In some list views, e.g. ARs, objects in various states are displayed together and all applicable buttons are displayed and it is possible that if multiple objects are selected and, e.g. [verify] is pressed, some objects in the selection don't comply with prerequisites. Thus far the system would just ignore those. 

https://github.com/bikalabs/Bika-LIMS/issues/855 Requests a warning or information message be displayed to the user. A better (proposed by rockfruit) would be to only show the appropriate buttons after the objects were selected (or grey the inappropriate ones out)

Nr 4 could possibly be spun out as a separate feature request...
